/**
 * generate_en_cn_variations.mjs
 * Run: node scripts/generate_en_cn_variations.mjs
 * Injects 100 EN + 100 CN variations (translated from the JA patterns) into videoTexts.ts
 */
import fs from 'fs';

// ─── Translation table: { [JA-id]: { hook:[EN,CN], empathy:[EN,CN], appReveal:[EN,CN] } }
const translations = {
    'JA-001': { hook: ["I know 'waiting is the job.' I still overtraded 16 times today.", "明知道「等待就是工作」，今天我还是进场了16次。"], empathy: ["It's not your strategy that's broken.\nYour fingers just won't stop.", "不是你的策略有问题。\n是你的手停不下来。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-002': { hook: ["No signal, just a 'feeling.' That's when overtrading starts.", "没有信号，只是「感觉可以」。那一刻就是频繁交易的开始。"], empathy: ["The only way to stop emotional trading\nis to physically stop yourself.", "阻止情绪化交易的唯一方法，\n就是物理上阻止自己。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-003': { hook: ["I averaged down 5 times today. That's what overtrading really looks like.", "今天我加仓5次。这就是频繁交易的真实面目。"], empathy: ["'Just once more' never stays\nat just once.", "「就这一次」从来不会只有一次。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-004': { hook: ["No position feels like losing. So I enter again. Every single time.", "没有持仓感觉就像在亏损。所以我又进场了。每一次都是这样。"], empathy: ["The time you're NOT in the market\nis your best trade.", "不在市场中的时间，\n才是你最好的交易。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-005': { hook: ["I re-entered the same direction 60 seconds after my stop. Everyone does this.", "止损后60秒我又反向进场了。每个人都经历过这个。"], empathy: ["To prevent revenge trades,\ndon't let yourself open the app.", "要防止报复性交易，\n就不要让自己打开App。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-006': { hook: ["Demo: profitable. Live: 25 entries. The problem isn't your method.", "在模拟账户我能赚钱。在实盘我进场了25次。问题不在你的方法。"], empathy: ["It's not your skill.\nIt's the anxiety driving you.", "不是你的技术。\n是焦虑在驱使你。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-007': { hook: ["Last night I swore 'no trades tomorrow.' By 9 AM I already had a position.", "昨晚我发誓「明天不交易」。早上9点我已经有持仓了。"], empathy: ["Determination isn't enough.\nOnly a system actually works.", "光靠决心是不够的。\n只有系统才真正有效。"], appReveal: ["Secure your profits. Force-lock the app until morning.", "保住盈利。强制锁定App到早上。"] },
    'JA-008': { hook: ["'Just one more contract.' 'Just 10 more minutes.' That loop drains your account.", "「就再做一单」「就再等10分钟」。这个循环正在掏空你的账户。"], empathy: ["'Just one more' is what 99%\nof overtrade addicts always say.", "「就再来一次」是99%的频繁交易者\n永远挂在嘴边的话。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-009': { hook: ["I even changed my chart colors. And still lost.", "我甚至换了图表颜色。还是亏了。"], empathy: ["Overtrading won't be fixed\nby more 'research.'", "频繁交易不是靠更多「研究」\n能解决的。"], appReveal: ["Take your phone out of your own hands.", "把手机的控制权，交给系统。"] },
    'JA-010': { hook: ["How many times have you thought 'next trade will be it' while watching spreads widen?", "当点差扩大时，你脑子里想过多少次「下一单一定行」？"], empathy: ["Willpower can't fix this.\nThat's just how the human brain works.", "意志力无法解决这个问题。\n这就是人脑的运作方式。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-066': { hook: ["'Just one more candle.' Next thing I know, 3 hours have passed.", "「就再看一根K线」。结果3个小时过去了。"], empathy: ["Charts have gravity.\nYou need a system to break free.", "图表有引力。\n你需要一个系统来挣脱它。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-067': { hook: ["Checking my phone dozens of times a day. Charts during meals. Charts at work. Not normal.", "一天查手机几十次。吃饭时看图。工作时看图。这不正常。"], empathy: ["The day the chart becomes the center of your life\nis day one of addiction.", "当图表成为你生活核心的那天，\n就是成瘾的第一天。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-069': { hook: ["I was 100% certain that level would hold. It didn't.", "我100%确定那个位置能守住。结果没有。"], empathy: ["Confidence level and win rate\nare not correlated.", "你有多确信和胜率，\n没有关联。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-011': { hook: ["Cut ¥50K loss, revenge doubled to ¥100K. Total hole: ¥150K.", "止损5万，加倍到10万去报复。总亏损：15万。"], empathy: ["The idea of 'winning it back'\nis casino thinking in disguise.", "「把钱赢回来」这个想法，\n本质就是赌场思维。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-012': { hook: ["3 losses by morning. Vowed to recover by noon. By night, account was half.", "早上亏了3次。发誓中午要追回来。到晚上，账户少了一半。"], empathy: ["Revenge trading has no logic.\nOnly rage.", "报复性交易没有逻辑。\n只有愤怒。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-013': { hook: ["I've doubled down for revenge and lost twice as much — three times.", "我已经三次用2倍的仓位报复，然后亏了2倍。"], empathy: ["Revenge trading is pure human instinct.\nThe only fix is a system that blocks it.", "报复性交易是人类的本能。\n唯一的解决方法是一个能封锁它的系统。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-014': { hook: ["'This losing streak can't continue' is the gambler's fallacy. Markets don't know your run.", "认为「这个亏损不可能继续」是赌徒谬误。市场不知道你的连败。"], empathy: ["Your gut instinct when anxious\nis wrong 95% of the time.", "你焦虑时的直觉判断，\n95%的概率是错的。"], appReveal: ["Secure your profits. Force-lock the app until morning.", "保住盈利。强制锁定App到早上。"] },
    'JA-071': { hook: ["10 losses in a row. That night: 'I'll recover in the night session.'", "连亏10次。那天晚上：「夜盘一定能追回来」。"], empathy: ["Trading with an exhausted brain\nis the fastest way to lose more.", "用耗尽的大脑进行交易，\n是亏损更多的最快方式。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-072': { hook: ["Day after a big loss, I said 'yesterday's setup was wrong.' Then did the same thing.", "大亏后的第二天，我说「昨天的策略不对」。然后做了同样的事。"], empathy: ["People who blame external factors for losses\nrepeat the same mistakes.", "把亏损归因于外部因素的人，\n会不断重蹈覆辙。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-075': { hook: ["Winning back the exact amount I lost still doesn't feel like recovery. That's the trap.", "就算赚回了完全相同的亏损金额，感觉上也没有「追回来」。这就是陷阱。"], empathy: ["Emotions don't get satisfied by numbers.\nThat's why it never ends.", "感情不会因为数字而满足。\n这就是为什么它永无止境。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-018': { hook: ["3 days after payday. ¥150K gone. My rent money evaporated.", "发薪日3天后，15万日元消失了。我的房租钱蒸发了。"], empathy: ["Regret comes after the trade closes,\nwhen your emotions finally cool.", "后悔在交易结束后才来，\n在你的情绪终于冷静之后。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-019': { hook: ["Took 6 months to build ¥500K. 1 week to lose it. That's leverage.", "花了6个月积累了50万日元。花了1周亏掉。这就是杠杆。"], empathy: ["Losses happen in an instant.\nDiscipline is built one day at a time.", "亏损发生在一瞬间。\n纪律要一天一天地建立。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-020': { hook: ["I keep saying 'just this month's spare cash' — but now I've touched my living expenses.", "我一直说「就用这个月的多余资金」——但现在动用了生活费。"], empathy: ["This is how FX dependency starts.", "这就是FX依赖的开始。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-021': { hook: ["Started as a side hustle. Now my FX losses exceed my salary.", "一开始把它当副业。现在我的FX亏损超过了工资。"], empathy: ["The illusion of 'I can win'\nkeeps the losses invisible.", "「我能赢」的幻觉，\n让你看不见真实的亏损。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-022': { hook: ["Raise your hand if you moved your NISA savings 'temporarily' into FX.", "有没有人曾经「临时」把NISA存款挪去做FX？举手。"], empathy: ["'Temporary' never becomes permanent.\nIt just becomes permanent loss.", "「临时」永远不会变成永久的。\n它只会变成永久的亏损。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-051': { hook: ["On my student loan repayment day, I lost the exact same amount in FX.", "学生贷款还款日那天，我在FX亏了同样金额的钱。"], empathy: ["Trying to grow money and losing what you had.\nThat's the dependency trap.", "想要赚更多钱，结果连本金也赔了。\n这就是依赖的陷阱。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-052': { hook: ["I put my ¥2M retirement savings into FX. Now I have ¥830K.", "我把200万日元的退休金存款投入FX。现在只剩83万日元。"], empathy: ["Anxiety and greed are slowly\neating your future self.", "焦虑和贪婪正在慢慢吞噬你的未来。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-053': { hook: ["'I'll repay it when my salary comes in.' I've been saying that for months.", "「等发工资了就补回来」。这句话我说了好几个月了。"], empathy: ["Once you start dipping in,\nyou're no longer trading.", "一旦你开始动用它，\n你做的就不再是交易了。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-054': { hook: ["The month I deposited my entire bonus into FX, I hit my biggest loss ever.", "我把全部奖金存入FX的那个月，创下了有史以来最大的亏损。"], empathy: ["More capital just means\nbigger emotional trades.", "更多的资本只意味着\n更大的情绪化交易。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-055': { hook: ["Hiding my FX trading from my partner for 3 years. Waiting to 'win it back first.'", "向伴侣隐瞒FX交易已经3年了。等着把钱赚回来再说。"], empathy: ["As long as you can hide it,\nyou think you're still okay.", "只要还能隐瞒，\n你就以为自己还没问题。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-056': { hook: ["I told a friend 'I started with ¥1M and have ¥100K left.' Most shameful day of my life.", "我告诉朋友「我用100万开始，现在只剩10万」。我人生中最羞耻的一天。"], empathy: ["A loss isn't just a number.\nIt disappears with your self-respect.", "亏损不只是一个数字。\n它和你的自尊心一起消失。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-057': { hook: ["I should have set a lock before I ever touched my kid's education fund.", "在我动用孩子的教育基金之前，我就应该设置交易锁定。"], empathy: ["The worst decisions happen\nat the moment emotions are highest.", "最糟糕的决定，发生在\n情绪最高涨的那一刻。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-058': { hook: ["Borrowed from a credit line with a 'guaranteed plan to win it back.' My lowest point.", "我用信用贷款进场，带着「一定能赚回来」的计划。那是我最低谷的时刻。"], empathy: ["Trading with borrowed money\nis the final stop of dependency.", "用借来的钱交易，\n是依赖症的终点。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-059': { hook: ["My ¥3M emergency fund from before I was married. Zero after 2 years of FX.", "独身时存下的300万日元紧急备用金。2年FX之后归零。"], empathy: ["Emergency money exists for emergencies.\nNot for trading.", "紧急备用金是为紧急情况准备的。\n不是为了交易。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-060': { hook: ["I told myself the moving fund was 'just for one week of trading.' That was a lie.", "我告诉自己搬家基金「只用来交易一周」。那是谎言。"], empathy: ["As long as you can say 'just temporarily,'\nyou still haven't realized.", "只要你还能说「只是暂时的」，\n你就还没有真正认清自己。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-061': { hook: ["The ¥300K I set aside for taxes was gone before tax filing day.", "我为纳税预留的30万日元在报税前就消失了。"], empathy: ["Money lost to FX can never be\nrecovered by more FX.", "在FX中亏损的钱，\n永远无法用更多FX来弥补。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-062': { hook: ["'I'll double this in 3 months for our wedding fund.' The money is gone.", "「我3个月内把这些钱翻倍当婚礼基金」。那笔钱消失了。"], empathy: ["Using a dream as bait for a deposit\nis the highest-risk trade of all.", "用梦想作为入金的诱饵，\n是所有交易中风险最高的。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-063': { hook: ["Earning ¥5M a year but FX losses leave my disposable income near zero.", "年收入500万日元，但FX亏损让我的可支配收入接近零。"], empathy: ["Stop growing income first.\nStop the losses first.", "不要先想着增加收入。\n先止血。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-064': { hook: ["I used my medical emergency fund 'just a little' for FX. Then couldn't see a doctor when I got sick.", "我「就用一点」医疗备用金做FX。然后我生病了，去不起医院。"], empathy: ["Dependency systematically destroys\nthe foundation of your life.", "依赖症会系统性地摧毁\n你生活的基础。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-065': { hook: ["My father's ¥8M retirement lump sum. 2 years 'trying to grow it a little.' Now gone.", "我父亲800万日元的退休金。2年「想稍微增值一下」。现在没了。"], empathy: ["More information won't help\nif emotional control is zero.", "如果情绪控制力为零，\n再多的信息也没用。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-023': { hook: ["2 AM. Can't sleep. Staring at USD/JPY, wondering if I should add to my short.", "凌晨2点。睡不着。盯着美元日元，想着要不要加仓做空。"], empathy: ["Sleep-deprived trading is basically\na guaranteed losing trade.", "睡眠不足的交易，基本就等于\n一笔注定亏损的交易。"], appReveal: ["Secure your profits. Force-lock the app until morning.", "保住盈利。强制锁定App到早上。"] },
    'JA-024': { hook: ["In a meeting. Charts on my phone. Didn't catch a single word of what was said.", "开会的时候。手机上看图表。会议上一个字也没听进去。"], empathy: ["The market has started\ninvading your real life.", "市场已经开始侵蚀\n你的现实生活了。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-025': { hook: ["Looking at my sleeping child's face while secretly checking the chart. I hate that version of me.", "看着孩子熟睡的脸，悄悄查看图表。我讨厌那个自己。"], empathy: ["FX doesn't only take money.\nIt takes everything.", "FX不只拿走钱。\n它拿走一切。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-026': { hook: ["Went to the toilet 5 times just to check price action. I knew that wasn't normal.", "上班时去了5次厕所只是为了看价格走势。我知道这不正常。"], empathy: ["This is what trading addiction\nactually looks like.", "这就是交易成瘾的\n真实面目。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-028': { hook: ["3 AM. Moved my stop loss down. Woke up to nothing but regret.", "凌晨3点。我把止损下移了。醒来只剩后悔。"], empathy: ["3 AM judgment is made by a completely\ndifferent brain than midday judgment.", "凌晨3点的判断，是由和中午\n完全不同的大脑做出的。"], appReveal: ["Secure your profits. Force-lock the app until morning.", "保住盈利。强制锁定App到早上。"] },
    'JA-029': { hook: ["Family asleep. Full leverage at midnight. Woke up to a margin call.", "家人睡觉了。午夜满仓杠杆入场。醒来收到追加保证金通知。"], empathy: ["'As long as no one finds out'\nis the worst decision-making standard.", "「只要没人发现就好」，\n是最糟糕的决策标准。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-076': { hook: ["Coworker said 'You've got really bad bags lately.' Late night trading does that.", "同事说「你最近黑眼圈好严重」。深夜交易造成的。"], empathy: ["Sleep debt kills your performance\nand steals your judgment.", "睡眠债会摧毁你的表现，\n也会偷走你的判断力。"], appReveal: ["Secure your profits. Force-lock the app until morning.", "保住盈利。强制锁定App到早上。"] },
    'JA-077': { hook: ["Started WFH. My FX losses tripled. The reason is obvious.", "开始居家办公。我的FX亏损增加了3倍。原因很明显。"], empathy: ["More opportunity means overtrading\naccelerates.", "更多的机会意味着\n频繁交易会加速。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-080': { hook: ["Forgot to pick up my kid because I was watching charts. Even a winning trade can't undo that.", "我忘了去接孩子，因为我在看图表。就算那笔交易赢了，有些事情也无法弥补。"], empathy: ["Are you hurting the family\nyou wanted FX to protect?", "你是否正在伤害，\n你本想用FX来保护的家人？"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-030': { hook: ["I moved my stop loss 3 times. Then got auto-liquidated.", "我把止损移了3次。然后被强制平仓了。"], empathy: ["The only reason you can't cut losses:\nyou don't want to admit you're wrong.", "你无法止损的唯一原因：\n你不想承认自己错了。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-031': { hook: ["'It'll bounce if I wait.' My drawdown tripled.", "「再等等就会反弹」。我的浮亏变成了3倍。"], empathy: ["Hope and evidence are two\nvery different things.", "希望和依据是两回事。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-032': { hook: ["I had a stop order set. Then I manually cancelled it.", "我设置了止损单。然后我手动取消了它。"], empathy: ["Breaking the rules you set for yourself\nis the symptom of FX dependency.", "打破你为自己设定的规则，\n是FX依赖的症状。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-034': { hook: ["Seeing -¥100K and thinking 'I'm still fine' — your senses are numb.", "看到亏损10万日元还觉得「还好」——你的感觉已经麻木了。"], empathy: ["Financial numbness is an early symptom\nof FX addiction.", "金钱感觉麻木是FX成瘾的\n早期症状。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-081': { hook: ["'It'll turn around.' And now my unrealized loss is 2 months of salary.", "「很快就会好转的」。现在我的浮亏已经是两个月工资了。"], empathy: ["Baseless optimism is the\nmost expensive emotion.", "毫无根据的乐观，是最昂贵的情绪。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-083': { hook: ["My rule was 'cut at -2%.' I held to -10%. Every. Single. Time.", "我的规则是「亏2%就止损」。我每次都持有到-10%。每一次。"], empathy: ["If you can't follow the rules you set yourself,\nlet an external system do it.", "如果你无法遵守自己设定的规则，\n就让外部系统来替你执行。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-035': { hook: ["3 wins in a row. 'Maybe I have talent.' Next day: full leverage. You know the rest.", "连赢3次。「也许我真的有天赋」。第二天：满仓杠杆。你知道结果如何。"], empathy: ["A winning streak might be skill.\nOr luck. The next trade will reveal which.", "连胜可能是技术，也可能是运气。\n下一笔交易会揭晓答案。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-036': { hook: ["+¥200K last month. Lost it all and the principal this month.", "上个月盈利20万日元。这个月把它和本金都亏光了。"], empathy: ["Those who can't protect their wins\nwill never win consistently.", "无法保住盈利的人，\n永远无法持续获胜。"], appReveal: ["Secure your profits. Force-lock the app until morning.", "保住盈利。强制锁定App到早上。"] },
    'JA-086': { hook: ["+¥500K this month, maybe going pro. The next week: -¥800K.", "+50万日元这个月，也许要成为职业交易员了。下周：-80万。"], empathy: ["Markets don't eliminate humble traders.\nThey eliminate arrogant ones.", "市场不会淘汰谦逊的交易者。\n它淘汰傲慢的那些人。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-088': { hook: ["'Today I'm perfectly in the zone. I'm going to win.' That's the most dangerous state.", "「今天我状态完美。我一定能赢」。那是最危险的状态。"], empathy: ["Overconfidence is the trigger\nthat sets off overtrading.", "过度自信是引发频繁交易的导火索。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-090': { hook: ["'Last month worked, so I'll double my lot this month.' That's the trade that ruins accounts.", "「上个月不错，所以这个月把仓位翻倍」。那就是毁掉账户的那笔交易。"], empathy: ["Past success makes the next risk feel like\nwisdom instead of gambling.", "过去的成功让下一次冒险看起来像智慧，\n而不是赌博。"], appReveal: ["Secure your profits. Force-lock the app until morning.", "保住盈利。强制锁定App到早上。"] },
    'JA-039': { hook: ["Decided 'no trades today.' 30 minutes later I had a position.", "我决定「今天不交易」。30分钟后我已经有持仓了。"], empathy: ["It's not about willpower.\nYou need to physically make it impossible.", "这不是意志力的问题。\n你需要物理上让它变得不可能。"], appReveal: ["Take your phone out of your own hands.", "把手机的控制权，交给系统。"] },
    'JA-040': { hook: ["Blocking myself from the app raised my win rate more than any rule I ever made.", "封锁自己无法打开App，比我制定的任何交易规则都更能提高胜率。"], empathy: ["Discipline isn't built through willpower.\nIt's built through systems.", "纪律不是靠意志力建立的。\n它是靠系统建立的。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-041': { hook: ["After cutting a loss, I blocked the app. Revenge trades went to zero.", "止损后，我封锁了App。报复性交易降到了零。"], empathy: ["If you can't do it,\nyou don't have to do it.", "如果你做不到，\n你就不必做。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-091': { hook: ["'Just a 1-hour break' turned into 4 hours of chart watching. So just don't open it.", "「就休息1小时」结果看了4小时图表。那就从一开始不要打开。"], empathy: ["'Just a little' is impossible for humans.\nDigital detox needs a hard lock.", "「就一点点」对人类来说是不可能的。\n数字戒断需要硬性锁定。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-093': { hook: ["The moment you start looking for 'the next opportunity' after a stop — lock now.", "止损后开始寻找「下一个机会」的那一刻——现在就锁定。"], empathy: ["The next opportunity should be found\nafter your head cools down.", "下一个机会应该在\n头脑冷静下来之后再去寻找。"], appReveal: ["Take your phone out of your own hands.", "把手机的控制权，交给系统。"] },
    'JA-043': { hook: ["Thought 'I have no talent for FX.' Let's talk about emotional control instead.", "认为「我没有FX天赋」。让我们来谈谈情绪控制。"], empathy: ["Most losers aren't defeated by skill.\nThey're defeated by emotion.", "大多数亏损者不是被技术打败的。\n他们是被情绪打败的。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-044': { hook: ["1 year into FX. What remained: ¥400K loss and self-hatred.", "FX一年后。剩下的只有：40万日元亏损和自我厌恶。"], empathy: ["What you should be continuing is not 'effort'\nbut 'the right system.'", "你应该坚持的不是「努力」，\n而是「正确的系统」。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-045': { hook: ["12 months of 'this month will be different.' Still the same.", "12个月的「这个月会不一样」。还是一样。"], empathy: ["Change doesn't come from determination.\nIt comes from changing the environment.", "改变不来自决心。\n来自改变环境。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-046': { hook: ["I want to quit FX but I can't. By definition, that's addiction.", "我想戒掉FX但我做不到。按定义，这已经是成瘾了。"], empathy: ["Addiction isn't overcome by willpower.\nIt's managed through systems.", "成瘾不是靠意志力克服的。\n它是通过系统来管理的。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-047': { hook: ["Said 'if I lose today I'll quit' 100 times. I never quit.", "说过100次「今天如果亏损就要戒掉」。我没有戒掉。"], empathy: ["Anyone who can still say 'I'll quit'\nhasn't truly committed yet.", "还能说「我要戒掉」的人，\n还没有真正下定决心。"], appReveal: ["Take your phone out of your own hands.", "把手机的控制权，交给系统。"] },
    'JA-094': { hook: ["Every week 'this week will be different.' 6 months later, identical. That scares me.", "每周「这周会不一样」。6个月后还在说同样的话。这让我感到恐惧。"], empathy: ["Repeating isn't because your will is weak.\nIt's because there's no system.", "你一再重蹈覆辙不是因为意志薄弱。\n而是因为没有系统。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-095': { hook: ["I had more money and peace before I started FX. When did it go wrong?", "开始FX之前，我有更多钱，也更安心。是什么时候开始出问题的？"], empathy: ["If you want to go back to before,\nyou have to change your behavior.", "如果你想回到以前，\n你必须改变自己的行为。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-097': { hook: ["Tried to recover losses. Lost even more. In that moment I thought: 'I'm done.'", "我试图追回损失，却亏得更多。那一刻我想：「我完了」。"], empathy: ["You're not done.\nNow is the moment to change the system.", "你没有完了。\n现在是改变系统的时候。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-048': { hook: ["My friend who started FX same time as me is profitable. I'm still blowing up.", "和我同时开始FX的朋友是盈利的。我还在不断爆仓。"], empathy: ["The difference comes down to number of trades.\nFewer is more.", "差异归结于交易次数。\n越少越好。"], appReveal: ["Overtrading can't be fixed by willpower. Block it with a system.", "意志力无法解决频繁交易的问题。用系统来封锁它。"] },
    'JA-049': { hook: ["'30% monthly return' accounts get beaten long-term by the 'zero trades this month' account.", "「月化30%」的账户，长期上被「这个月零交易」的人打败。"], empathy: ["The best strategy isn't to outperform.\nIt's to not get eliminated.", "最好的策略不是跑赢市场。\n而是不被淘汰出局。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-050': { hook: ["Winning traders decide what NOT to do — not what to do.", "获胜的交易者决定什么「不做」——而不是什么「做」。"], empathy: ["Trade Block exists to protect\nyour 'no-trade decisions.'", "Trade Block的存在，是为了保护\n你的「不交易的决定」。"], appReveal: ["Take your phone out of your own hands.", "把手机的控制权，交给系统。"] },
    'JA-098': { hook: ["Still looking for a way to 'control it better' instead of quitting? Real talk incoming.", "还在找「更好地控制它」的方法而不是戒掉它？我们来说说实话。"], empathy: ["Addiction isn't solved by 'getting better at it.'\nOnly distance solves it.", "成瘾的解决方法不是「学会更好地处理它」。\n只有保持距离才能解决。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
    'JA-099': { hook: ["Every time I open the app: 'this is the last time.' Then I open it again. That's addiction.", "每次打开App我都想「这是最后一次」。然后我又打开了。这就是成瘾。"], empathy: ["For someone whose 'last time' never comes,\na physical wall is the answer.", "对于「最后一次」永远不会来临的人，\n物理屏障才是答案。"], appReveal: ["Block emotional trades with a system, not a promise.", "用系统，而不是承诺，来封锁情绪化交易。"] },
    'JA-100': { hook: ["What if all the mental energy you spend on trading went to your career and family?", "如果你把花在交易上的所有精神能量，转移到事业和家庭上，会怎样？"], empathy: ["FX takes not just money.\nIt takes time, focus, and relationships.", "FX不只拿走钱。\n它拿走时间、专注力和人际关系。"], appReveal: ["Force yourself out of the market. One system. No exceptions.", "强制让自己离开市场。一个系统，无例外。"] },
};

// ─── Read videoTexts.ts ───────────────────────────────────────────────────────
const srcPath = 'src/videoTexts.ts';
const content = fs.readFileSync(srcPath, 'utf-8');

const jaIds = Object.keys(translations);

const buildBlock = (id, langIdx, ctaText, lang) => {
    const t = translations[id];
    const newId = id.replace('JA-', lang === 'en' ? 'EN-' : 'CN-');
    return `  {\n    id: '${newId}',\n    props: {\n      hookText: ${JSON.stringify(t.hook[langIdx])},\n      empathyText: ${JSON.stringify(t.empathy[langIdx])},\n      appRevealText: ${JSON.stringify(t.appReveal[langIdx])},\n      ctaText: ${JSON.stringify(ctaText)},\n      bgImageSrc1A: DEFAULT_ASSETS.bgImageSrc1A,\n      bgImageSrc1B: DEFAULT_ASSETS.bgImageSrc1B,\n      bgImageSrc2A: DEFAULT_ASSETS.bgImageSrc2A,\n      bgImageSrc2B: DEFAULT_ASSETS.bgImageSrc2B,\n      bgImageSrc4: DEFAULT_ASSETS.bgImageSrc4,\n      videoSrc: DEFAULT_ASSETS.videoSrc,\n      lang: '${lang === 'en' ? 'en' : 'zh-CN'}' as const,\n    }\n  }`;
};

const enBlocks = jaIds.map(id => buildBlock(id, 0, 'Download Trade Block now.', 'en')).join(',\n');
const cnBlocks = jaIds.map(id => buildBlock(id, 1, '立即下载 Trade Block', 'cn')).join(',\n');

// Find insertion point — replace everything after the JA spread and before the closing ];
const insertionMark = '  // 英語バリエーション';
const idx = content.lastIndexOf(insertionMark);
if (idx === -1) { console.error('Insertion point not found'); process.exit(1); }

const newContent =
    content.slice(0, idx) +
    `  // 英語バリエーション（日本語100案の翻訳版）\n${enBlocks},\n\n  // 中国語バリエーション（日本語100案の翻訳版）\n${cnBlocks},\n];\n`;

fs.writeFileSync(srcPath, newContent);
console.log(`✅ Done! Injected ${jaIds.length} EN + ${jaIds.length} CN patterns.`);
